import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
import "./globals.scss";
import Header from "./components/navigation/header";
import Footer from "./components/navigation/footer";

const orbitron = Orbitron({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Armur",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${orbitron.className} relative`}>
        <div className=" min-h-screen overflow-hidden container mx-auto">
          <Header />
          <div className="main relative z-[9999]">{children}</div>
          <div className="footer-container h-auto">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
